from __future__ import annotations

import csv
import io
from datetime import datetime, timezone
from urllib.request import Request, urlopen

from .ma_breadth import build_ma_breadth_metrics, parse_ma_breadth_csv


DEFAULT_URL = (
    "https://tradermonty.github.io/market-breadth-analysis/"
    "market_breadth_data.csv"
)


class TraderMontyBreadthError(RuntimeError):
    pass


def fetch_tradermonty_csv(url: str = DEFAULT_URL, timeout: int = 30) -> str:
    req = Request(
        url,
        headers={
            "User-Agent": (
                "Market-Risk-Monitor/0.2 "
                "(https://github.com/world4jason/Market-Risk-Monitor)"
            )
        },
    )
    try:
        with urlopen(req, timeout=timeout) as response:
            return response.read().decode("utf-8-sig")
    except Exception as exc:
        raise TraderMontyBreadthError(
            f"failed to fetch TraderMonty breadth CSV: {exc}"
        ) from exc


def convert_tradermonty_csv(text: str) -> str:
    """
    Convert TraderMonty's public detail CSV into the MRM authorized-import contract.

    Important provenance caveat:
    TraderMonty's implementation fetches the *current* S&P 500 constituent list
    from FMP, then computes historical breadth from those symbols. Therefore
    historical rows are explicitly marked current_constituents_retroactive and
    are blocked from canonical MRM event studies / historical signals.
    """
    reader = csv.DictReader(io.StringIO(text))
    if not reader.fieldnames:
        raise TraderMontyBreadthError("TraderMonty CSV has no header")

    required = {"Date", "Breadth_Index_Raw"}
    missing = required - set(reader.fieldnames)
    if missing:
        raise TraderMontyBreadthError(
            f"TraderMonty CSV missing required columns: {sorted(missing)}"
        )

    has_50 = "Breadth_50_Index_Raw" in reader.fieldnames
    out = io.StringIO()
    fieldnames = [
        "date",
        "market_scope",
        "provider",
        "above_20dma_pct",
        "above_50dma_pct",
        "above_200dma_pct",
        "membership_mode",
        "membership_snapshot",
        "price_adjustment",
    ]
    writer = csv.DictWriter(out, fieldnames=fieldnames)
    writer.writeheader()

    count = 0
    for row in reader:
        raw_date = (row.get("Date") or "").strip()
        if not raw_date:
            continue

        raw_200 = (row.get("Breadth_Index_Raw") or "").strip()
        raw_50 = (row.get("Breadth_50_Index_Raw") or "").strip() if has_50 else ""

        try:
            pct_200 = None if raw_200 in {"", "nan", "NaN"} else 100.0 * float(raw_200)
            pct_50 = None if raw_50 in {"", "nan", "NaN"} else 100.0 * float(raw_50)
        except ValueError as exc:
            raise TraderMontyBreadthError(
                f"non-numeric breadth value on {raw_date}"
            ) from exc

        # Export only rows with at least one usable horizon.
        if pct_200 is None and pct_50 is None:
            continue

        writer.writerow(
            {
                "date": raw_date[:10],
                "market_scope": "S&P 500",
                "provider": "TraderMonty market-breadth-analysis / FMP",
                "above_20dma_pct": "",
                "above_50dma_pct": "" if pct_50 is None else f"{pct_50:.8f}",
                "above_200dma_pct": "" if pct_200 is None else f"{pct_200:.8f}",
                "membership_mode": "current_constituents_retroactive",
                "membership_snapshot": "current-FMP-constituents-at-generation",
                "price_adjustment": "adjusted_close",
            }
        )
        count += 1

    if count == 0:
        raise TraderMontyBreadthError("TraderMonty CSV contained no usable rows")
    return out.getvalue()


def build_tradermonty_metrics(
    text: str,
    fetched_at: datetime | None = None,
) -> dict[str, dict]:
    converted = convert_tradermonty_csv(text)
    rows = parse_ma_breadth_csv(converted)
    metrics = build_ma_breadth_metrics(
        rows,
        fetched_at=fetched_at or datetime.now(timezone.utc),
    )

    for metric in metrics.values():
        metric["source"]["url"] = DEFAULT_URL
        metric["source"]["license_note"] = (
            "Public CSV generated by the MIT-licensed TraderMonty project from "
            "FMP data. Historical membership is current-constituent retroactive; "
            "MRM therefore blocks it from canonical historical event studies. "
            "Underlying data rights remain subject to the upstream provider."
        )
        metric["source"]["redistribution"] = "unknown"
        metric["lineage"]["transform_version"] = "tradermonty-ma-breadth-v1"
    return metrics
